### ISSUE TITLE
[Bug]: Getting error when trying to install Pimcore skeleton v10.5.13

### ISSUE THREAD

**Issue by syncrasy-git** [pimcore/skeleton#130] opened 2022-12-29 12:48 UTC
### Expected behavior

I should be able to access both front-end and admin panel of Pimcore.

### Actual behavior

Unable to access admin panel of Pimcore skeleton v10.5.13. Tried installing using docker based on the predefine docker-compose.yml
![Uploading Screenshot from 2022-12-29 18-15-14.png…]()

twig_matches(): Argument #2 ($str) must be of type string, null given, called in /var/www/html/var/cache/dev/twig/6d/6d7d7144a0d9841000a8f80619c140a9.php on line 91

### Steps to reproduce

Follow these steps
Initialize the skeleton project using the pimcore/pimcore image docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.1-latest composer create-project pimcore/skeleton my-project

Go to your new project cd my-project/

Part of the new project is a docker compose file

Run echo `id -u`:`id -g` to retrieve your local user and group id
Open the docker-compose.yml file in an editor, uncomment all the user: '1000:1000' lines and update the ids if necessary
Start the needed services with docker-compose up -d
Install pimcore and initialize the DB docker-compose exec php vendor/bin/pimcore-install --mysql-host-socket=db --mysql-username=pimcore --mysql-password=pimcore --mysql-database=pimcore

**Comment by jdreesen** [comment] 2022-12-29 13:17
Seems like a duplicate of #129. Not sure why the other one was closed, though.

**Comment by jdreesen** [comment] 2022-12-29 13:20
Apart from that: it doesn't look like you installed `v10.5.13`, but `v11.0.0-ALPHA1`, which may be broken.

**Comment by syncrasy-git** [comment] 2022-12-29 13:26
It could be, however the composer.json file still has pimcore version 10.5 and I am using the same file to install.

{
  "name": "pimcore/skeleton",
  "type": "project",
  "license": "GPL-3.0-or-later",
  "config": {
    "optimize-autoloader": true,
    "sort-packages": true,
    "process-timeout": 0
  },
  "require": {
    "pimcore/pimcore": "^10.5"
  },

**Comment by kingjia90** [comment] 2022-12-29 14:36
> Seems like a duplicate of #129. Not sure why the other one was closed, though.

i've also took a quick look, don't see any usage of this `twig_matches` in Pimcore itself, maybe it was closed because it's a [third-party BC break problem ](https://github.com/twigphp/Twig/blob/3ffcf4b7d890770466da3b2666f82ac054e7ec72/CHANGELOG#L6) and it was released just 2 days ago in `twig\twig` 3.5.0

A temporary solution would be force composer to require a twig/twig < 3.5, maybe Pimcore would need to add a `conflict` line

https://github.com/twigphp/Twig/commit/61672c43f97dc2a9197211997e0ec2b1a797444c#diff-29e85e483c6ec4a9c2fd144820b6722c86df60d54175b355d85e806253313c1aR1031

**Comment by jdreesen** [comment] 2022-12-29 14:51
I don't think it's `twig_matches` but `matches` in twig templates, which is used three times by pimcore: https://github.com/search?q=repo%3Apimcore%2Fpimcore+matches+language%3ATwig&type=code&l=Twig

**Comment by jdreesen** [comment] 2022-12-29 14:54
I suppose in one of them the variable is `null` instead of some string, so an additional check is probably needed.

**Comment by kingjia90** [comment] 2022-12-29 17:34
> I don't think it's `twig_matches` but `matches` in twig templates, which is used three times by pimcore: https://github.com/search?q=repo%3Apimcore%2Fpimcore+matches+language%3ATwig&type=code&l=Twig

ahh, nice catch, it's the one in https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/templates/admin/login/layout.html.twig#L22
![image](https://user-images.githubusercontent.com/6014195/209988036-f85e3880-8809-4875-8faf-eace92971a70.png)


changing
https://github.com/pimcore/pimcore/blob/38419b06c61565e62122e32684e37c102cbe25d2/bundles/AdminBundle/templates/admin/login/layout.html.twig#L19
to something like
`{% set customImage = config['branding']['login_screen_custom_image'] ?? '' %}` works but the issue might be related to  `/var/config/system.yml` not being populated on initialization

**Comment by kingjia90** [comment] 2023-01-04 10:03
Fixed by https://github.com/pimcore/pimcore/pull/13948

**Closed as completed by kingjia90** 2023-01-04 10:03 UTC
